### ISSUE TITLE
KeyError: 'dataset/deepfashionHD\\img\\MEN\\Denim\\id_00000089\\02_7_additional.jpg'

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [microsoft/CoCosNet-v2#15]
When I am running the project from the following command
```
python ./test.py --name deepfashionHD --dataset_mode deepfashionHD --dataroot dataset/deepfashionHD --PONO --PONO_C --no_flip --batchSize 8 --gpu_ids 0 --netCorr NoVGGHPM --nThreads 16 --nef 32 --amp --display_winsize 512 --iteration_count 5 --load_size 512 --crop_size 512
```
then I am getting the following error:
```
Traceback (most recent call last):
  File "./test.py", line 25, in <module>
    for i, data_i in enumerate(dataloader):
  File "C:\ProgramData\Anaconda3\envs\init_CoCosNet_V2_231021\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\init_CoCosNet_V2_231021\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\init_CoCosNet_V2_231021\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\init_CoCosNet_V2_231021\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\init_CoCosNet_V2_231021\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\init_CoCosNet_V2_231021\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\init_CoCosNet_V2_231021\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\PycharmProjects_04_05_2021\init_CoCosNet_V2_231021\data\pix2pix_dataset.py", line 72, in __getitem__
    val = self.ref_dict[key]
KeyError: 'dataset/deepfashionHD\\img\\MEN\\Denim\\id_00000089\\02_7_additional.jpg'
```
Can anyone please help me in solving this.

**Comment by mayanktiwariiiitdmj** [comment]
I have also changed the "\\" to "/" in the Key.
Now the Key is having value as:

'deepfashionHD/img/MEN/Denim/id_00000089/02_7_additional.jpg'
